version: "3.8"

services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: s_day
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3308"

  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    image: anrimy/sb_board
    ports:
      - "5000:8080"
    container_name: sb_board
    restart: always
    depends_on:
      - database